"""initial schema

Revision ID: 2d16b4d95bec
Revises: 
Create Date: 2026-09-10 20:01:17.392162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2d16b4d95bec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('org_name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ua', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_ts', ['action', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'channel_id', name='uq_channel_device')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_device_id'), ['device_id'], unique=False)

    op.create_table('orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('ip_whitelist', sa.Text(), nullable=True),
    sa.Column('max_concurrent_plays', sa.Integer(), nullable=False),
    sa.Column('quota_gb', sa.Integer(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('channel_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('can_live', sa.Boolean(), nullable=False),
    sa.Column('can_playback', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_grant_user_channel')
    )
    with op.batch_alter_table('channel_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_grants_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_grants_user_id'), ['user_id'], unique=False)

    op.create_table('download_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('wvp_stream', sa.String(length=128), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_tasks_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('play_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('app', sa.String(length=32), nullable=False),
    sa.Column('stream', sa.String(length=128), nullable=False),
    sa.Column('stream_token', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('play_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_play_sessions_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_play_sessions_stream_token'), ['stream_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_play_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('play_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_play_sessions_stream_token'))
        batch_op.drop_index(batch_op.f('ix_play_sessions_channel_id'))

    op.drop_table('play_sessions')
    with op.batch_alter_table('download_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_download_tasks_channel_id'))

    op.drop_table('download_tasks')
    with op.batch_alter_table('channel_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_grants_user_id'))
        batch_op.drop_index(batch_op.f('ix_channel_grants_channel_id'))

    op.drop_table('channel_grants')
    op.drop_table('users')
    op.drop_table('orgs')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_device_id'))
        batch_op.drop_index(batch_op.f('ix_channels_channel_id'))

    op.drop_table('channels')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_action_ts')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
