"""add channel pause_supported

Revision ID: 8199feb72b12
Revises: 2d16b4d95bec
Create Date: 2026-09-11 09:41:03.866687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8199feb72b12'
down_revision: Union[str, None] = '2d16b4d95bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause_supported', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_column('pause_supported')

    # ### end Alembic commands ###
